### ISSUE TITLE
Ejecutar Seeder en una linea

### ISSUE THREAD

**Issue by JMEspiz** [LaravelVe/OzonoCMS#16]
Buenas tardes, que les parece si en vez de correr cada seeder por separado mejor agruparlos en **DatabaseSeeder.php**.

de esta manera quien necesite generar información con los seeder solo tenga que usar:

```php

php artisan migrate --seed

```

Enviare el PR con lo que mencione, dependiendo de su opinión puede aceptarlo o rechazarlo.

Saludos.

**Comment by raicoacosta** [comment]
Si es que esa deberia ser la forma como se deben llevar.

**Comment by abr4xas** [comment]
Tienes razón, así es como se debe hacer :smile: 

Agregado en 2821de1

**Comment by raicoacosta** [comment]
Se aprobó una mejora para el modo en el que corre los seeder.
