### ISSUE TITLE
Install Entrust

### ISSUE THREAD

**Issue by CrafterSama** [LaravelVe/OzonoCMS#3]
Install Entrust To manage users role permissions

run the Command composer require zizaco/entrust:5.2.x-dev

**Comment by raicoacosta** [comment]
Si tines algún inconveniente al instalar mas allá de la documentacion oficial comentas acá

https://github.com/Zizaco/entrust

**Comment by oteroweb** [comment]
Yo configuro Entrust

**Comment by oteroweb** [comment]
ya esta configurado 👍

**Comment by raicoacosta** [comment]
@oteroweb This issue is assignet to @CrafterSama

**Comment by CrafterSama** [comment]
No se si esta listo así o Necesitas que haga la relación, que supongo que es idéntica a la normal...

**Comment by abr4xas** [comment]
Hola, estaba probando Ozono y me salieron los siguientes errores:

```
[Illuminate\Database\QueryException]                                                                                                                                 
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: alter table `role_user` add constraint `role_user_user_id_foreign` foreign ke  
  y (`user_id`) references `` (`id`) on delete cascade on update cascade)
```

Y esto:

```
[PDOException]                                                                   
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''
```
